# Generated by Django 2.1.2 on 2018-12-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(height_field=660, upload_to='post', width_field=680)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.Post'),
        ),
    ]
